global:
  scrape_interval: 30s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tourism-website'

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
